### ISSUE TITLE
The update build target does not work for the actor template

### ISSUE THREAD

**Issue by matsbror** [wasmCloud/project-templates#17]
The getting started tutorial mentions using `make update` to make sure the registry has the new version of an actor. This code is commented out in the file `actor.mk` as it needs an automatic revision update.

**Comment by brooksmtownsend** [comment]
@stevelr bump on this, looks like we can likely resolve this issue with a combination of https://github.com/wasmCloud/wash/issues/193 and a recent PR to use the `iat` value in place of revision. I'd say this depends on the linked `wash` PR.

**Comment by stevelr** [comment]
I haven't had time to test `make update` with the iat change yet. I'll try to get to it later this week.

**Comment by stevelr** [comment]
Per my testing, live actor update it still doesn't work from wash.
- build echo actor, link, run it, test with curl - ok so far
- make a small change, rebuild.
- tried 'make update' and it failed with `U.nable to perform live update: error`  not a helpful error message since it doesn't explain why. 
- tried `wash drain all` and pushed it to the local registry, then `make update` and get same error
- restarted the registry in case there's a problem with pushing the same tag version
- `make update` gets same error
- `wash drain all` again and `make update`: same error

That error comes from the otp host control_interface/server.ex, after returning from actor supervisor live_update. live update emits a log message "Performing live update ...",  which never shows in the logs so the error must be occurring before that.

**Comment by stevelr** [comment]
Still doesn't work if you recompile, `wash drain all` push to the registry with the same tag, and try to update.
Even tried restarting the registry and re-pushing the actor.

The purpose of the `iat` change was that developers shouldn't have to bump the version number in the makefile for each recompile.
The host emits the error: "Unable to perform live update: error" - not an error message that provides any help to the developer to understand why it didn't work.

That error comes from the otp host control_interface/server.ex, after returning from actor supervisor live_update. The live_update function has an instruction to log "Performing live update ...", but that message never appears in the log, so the error probably occurs before the Logger instruction.

**Comment by stevelr** [comment]
@brooksmtownsend this shouldn't be blocked by https://github.com/wasmCloud/wash/issues/193, if we can use `wash drain all`, right?

**Comment by brooksmtownsend** [comment]
> @brooksmtownsend this shouldn't be blocked by https://github.com/wasmCloud/wash/issues/193, if we can use `wash drain all`, right?

Yes to solve this initially we can just use drain all

**Comment by brooksmtownsend** [comment]
No longer applies, no Makefiles
